### ISSUE TITLE
About vanced microg 

### ISSUE THREAD

**Issue by Mohammed1520** [cuynu/VancedMicroG#2]
I know that inotia00 discontinued vanced microg. But i want to ask you if you could update vanced microg regularly? It's more smooth and better than the new mMicrog. Could you please put that into your considerations?

**Comment by cuynu** [comment]
inotia00 discontinued Vanced microG as oxrxl provide mMicroG code to fix chromecaat v2 but it only is temporary solution. Manager of ReVanced Team is now implementing new microG, you can check it here https://github.com/oSumAtrIX/GmsCore
I probably discontinue Vanced microG after ReVanced Team implemented new microG or continue but only bump GMS version and dependency.
