### ISSUE TITLE
Xiaomi Home notifications problem

### ISSUE THREAD

**Issue by djsolidsnake86** [cuynu/VancedMicroG#3]
Hello, i think there is some sort of incompatibility with vancedmicro (all versions) and xiaomi home push notifications, actually after install vancedmicrog i lose the xiaomi home push notifications (that use xiaomi mi push service, not android push service)
can you check if there is some incompatibility? thanks

**Comment by cuynu** [comment]
not related to Vanced microG, its maybe because MIUI sucks
